//Background  , Color ID: 0
//White   , Color ID: 1
//Pale Weak Yellow	, Color ID: 2
//Pale Dull Yellow	, Color ID: 3
//Light Faded Yellow	, Color ID: 4
//Light Hard Yellow	, Color ID: 5
//Yellow  , Color ID: 6
//Pale Weak Cyan	, Color ID: 7
//Pale Weak Green	, Color ID: 8
//Pale Dull Spring	, Color ID: 9
//Light Spring Yellow	, Color ID: 10
//Light Yellow Spring	, Color ID: 11
//Yellow Yellow Spring	, Color ID: 12
//Pale Dull Cyan	, Color ID: 13
//Pale Dull Teal	, Color ID: 14
//Pale Dull Green	, Color ID: 15
//Light Spring Green	, Color ID: 16
//Light Hard Spring	, Color ID: 17
//Spring Spring Yellow	, Color ID: 18
//Light Faded Cyan	, Color ID: 19
//Light Teal Cyan	, Color ID: 20
//Light Teal Green	, Color ID: 21
//Light Faded Green	, Color ID: 22
//Light Green Spring	, Color ID: 23
//Spring Spring Green	, Color ID: 24
//Light Hard Cyan	, Color ID: 25
//Light Cyan Teal	, Color ID: 26
//Light Hard Teal	, Color ID: 27
//Light Green Teal	, Color ID: 28
//Light Hard Green	, Color ID: 29
//Green Green Spring	, Color ID: 30
//Cyan    , Color ID: 31
//Cyan Cyan Teal	, Color ID: 32
//Teal Teal Cyan	, Color ID: 33
//Teal Teal Green	, Color ID: 34
//Green Green Teal	, Color ID: 35
//Green   , Color ID: 36
//Pale Weak Magenta	, Color ID: 37
//Pale Weak Red	, Color ID: 38
//Pale Dull Orange	, Color ID: 39
//Light Orange Yellow	, Color ID: 40
//Light Yellow Orange	, Color ID: 41
//Yellow Yellow Orange	, Color ID: 42
//Pale Weak Blue	, Color ID: 43
//Pale Gray, Color ID: 44
//Light Weak Yellow	, Color ID: 45
//Light Dull Yellow	, Color ID: 46
//Medium Faded Yellow	, Color ID: 47
//Dark Hard Yellow	, Color ID: 48
//Pale Dull Azure	, Color ID: 49
//Light Weak Cyan	, Color ID: 50
//Light Weak Green	, Color ID: 51
//Light Dull Spring	, Color ID: 52
//Medium Spring Yellow	, Color ID: 53
//Dark Yellow Spring	, Color ID: 54
//Light Azure Cyan	, Color ID: 55
//Light Dull Cyan	, Color ID: 56
//Light Dull Teal	, Color ID: 57
//Light Dull Green	, Color ID: 58
//Medium Spring Green	, Color ID: 59
//Dark Hard Spring	, Color ID: 60
//Light Cyan Azure	, Color ID: 61
//Medium Faded Cyan	, Color ID: 62
//Medium Teal Cyan	, Color ID: 63
//Medium Teal Green	, Color ID: 64
//Medium Faded Green	, Color ID: 65
//Dark Green Spring	, Color ID: 66
//Cyan Cyan Azure	, Color ID: 67
//Dark Hard Cyan	, Color ID: 68
//Dark Cyan Teal	, Color ID: 69
//Dark Hard Teal	, Color ID: 70
//Dark Green Teal	, Color ID: 71
//Dark Hard Green	, Color ID: 72
//Pale Dull Magenta	, Color ID: 73
//Pale Dull Pink	, Color ID: 74
//Pale Dull Red	, Color ID: 75
//Light Orange Red	, Color ID: 76
//Light Hard Orange	, Color ID: 77
//Orange Orange Yellow	, Color ID: 78
//Pale Dull Violet	, Color ID: 79
//Light Weak Magenta	, Color ID: 80
//Light Weak Red	, Color ID: 81
//Light Dull Orange	, Color ID: 82
//Medium Orange Yellow	, Color ID: 83
//Dark Yellow Orange	, Color ID: 84
//Pale Dull Blue	, Color ID: 85
//Light Weak Blue	, Color ID: 86
//Light Gray, Color ID: 87
//Medium Weak Yellow	, Color ID: 88
//Dark Dull Yellow	, Color ID: 89
//Dark Faded Yellow	, Color ID: 90
//Light Azure Blue	, Color ID: 91
//Light Dull Azure	, Color ID: 92
//Medium Weak Cyan	, Color ID: 93
//Medium Weak Green	, Color ID: 94
//Dark Dull Spring	, Color ID: 95
//Dark Spring Yellow	, Color ID: 96
//Light Hard Azure	, Color ID: 97
//Medium Azure Cyan	, Color ID: 98
//Dark Dull Cyan	, Color ID: 99
//Dark Dull Teal	, Color ID: 100
//Dark Dull Green	, Color ID: 101
//Dark Spring Green	, Color ID: 102
//Azure Azure Cyan	, Color ID: 103
//Dark Cyan Azure	, Color ID: 104
//Dark Faded Cyan	, Color ID: 105
//Dark Teal Cyan	, Color ID: 106
//Dark Teal Green	, Color ID: 107
//Dark Faded Green	, Color ID: 108
//Light Faded Magenta	, Color ID: 109
//Light Pink Magenta	, Color ID: 110
//Light Pink Red	, Color ID: 111
//Light Faded Red	, Color ID: 112
//Light Red Orange	, Color ID: 113
//Orange Orange Red	, Color ID: 114
//Light Violet Magenta	, Color ID: 115
//Light Dull Magenta	, Color ID: 116
//Light Dull Pink	, Color ID: 117
//Light Dull Red	, Color ID: 118
//Medium Orange Red	, Color ID: 119
//Dark Hard Orange	, Color ID: 120
//Light Violet Blue	, Color ID: 121
//Light Dull Violet	, Color ID: 122
//Medium Weak Magenta	, Color ID: 123
//Medium Weak Red	, Color ID: 124
//Dark Dull Orange	, Color ID: 125
//Dark Orange Yellow	, Color ID: 126
//Light Faded Blue	, Color ID: 127
//Light Dull Blue	, Color ID: 128
//Medium Weak Blue	, Color ID: 129
//Dark Gray, Color ID: 130
//Dark Weak Yellow	, Color ID: 131
//Obscure Dull Yellow	, Color ID: 132
//Light Blue Azure	, Color ID: 133
//Medium Azure Blue	, Color ID: 134
//Dark Dull Azure	, Color ID: 135
//Dark Weak Cyan	, Color ID: 136
//Dark Weak Green	, Color ID: 137
//Obscure Dull Spring	, Color ID: 138
//Azure Azure Blue	, Color ID: 139
//Dark Hard Azure	, Color ID: 140
//Dark Azure Cyan	, Color ID: 141
//Obscure Dull Cyan	, Color ID: 142
//Obscure Dull Teal	, Color ID: 143
//Obscure Dull Green	, Color ID: 144
//Light Hard Magenta	, Color ID: 145
//Light Magenta Pink	, Color ID: 146
//Light Hard Pink	, Color ID: 147
//Light Red Pink	, Color ID: 148
//Light Hard Red	, Color ID: 149
//Red Red Orange	, Color ID: 150
//Light Magenta Violet	, Color ID: 151
//Medium Faded Magenta	, Color ID: 152
//Medium Pink Magenta	, Color ID: 153
//Medium Pink Red	, Color ID: 154
//Medium Faded Red	, Color ID: 155
//Dark Red Orange	, Color ID: 156
//Light Hard Violet	, Color ID: 157
//Medium Violet Magenta	, Color ID: 158
//Dark Dull Magenta	, Color ID: 159
//Dark Dull Pink	, Color ID: 160
//Dark Dull Red	, Color ID: 161
//Dark Orange Red	, Color ID: 162
//Light Blue Violet	, Color ID: 163
//Medium Violet Blue	, Color ID: 164
//Dark Dull Violet	, Color ID: 165
//Dark Weak Magenta	, Color ID: 166
//Dark Weak Red	, Color ID: 167
//Obscure Dull Orange	, Color ID: 168
//Light Hard Blue	, Color ID: 169
//Medium Faded Blue	, Color ID: 170
//Dark Dull Blue	, Color ID: 171
//Dark Weak Blue	, Color ID: 172
//Obscure Gray, Color ID: 173
//Obscure Weak Yellow	, Color ID: 174
//Blue Blue Azure	, Color ID: 175
//Dark Blue Azure	, Color ID: 176
//Dark Azure Blue	, Color ID: 177
//Obscure Dull Azure	, Color ID: 178
//Obscure Weak Cyan	, Color ID: 179
//Obscure Weak Green	, Color ID: 180
//Magenta , Color ID: 181
//Magenta Magenta Pink	, Color ID: 182
//Pink Pink Magenta	, Color ID: 183
//Pink Pink Red	, Color ID: 184
//Red Red Pink	, Color ID: 185
//Red , Color ID: 186
//Magenta Magenta Violet	, Color ID: 187
//Dark Hard Magenta	, Color ID: 188
//Dark Magenta Pink	, Color ID: 189
//Dark Hard Pink	, Color ID: 190
//Dark Red Pink	, Color ID: 191
//Dark Hard Red	, Color ID: 192
//Violet Violet Magenta	, Color ID: 193
//Dark Magenta Violet	, Color ID: 194
//Dark Faded Magenta	, Color ID: 195
//Dark Pink Magenta	, Color ID: 196
//Dark Pink Red	, Color ID: 197
//Dark Faded Red	, Color ID: 198
//Violet Violet Blue	, Color ID: 199
//Dark Hard Violet	, Color ID: 200
//Dark Violet Magenta	, Color ID: 201
//Obscure Dull Magenta	, Color ID: 202
//Obscure Dull Pink	, Color ID: 203
//Obscure Dull Red	, Color ID: 204
//Blue Blue Violet	, Color ID: 205
//Dark Blue Violet	, Color ID: 206
//Dark Violet Blue	, Color ID: 207
//Obscure Dull Violet	, Color ID: 208
//Obscure Weak Magenta	, Color ID: 209
//Obscure Weak Red	, Color ID: 210
//Blue    , Color ID: 211
//Dark Hard Blue	, Color ID: 212
//Dark Faded Blue	, Color ID: 213
//Obscure Dull Blue	, Color ID: 214
//Obscure Weak Blue	, Color ID: 215
//Black   , Color ID: 216