//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\arunk\source\repos\ModelingPractice\UserInterface\UI_ObjectSelectionToDisplayDetails.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: arunk
//              Version: NX 12
//              Date: 06-13-2026  (Format: mm-dd-yyyy)
//              Time: 10:37 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using System.IO;
using ModelingPractice;
using NXOpen;
using NXOpen.BlockStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class UI_ObjectSelectionToDisplayDetails
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group group0;// Block type: Group
    private NXOpen.BlockStyler.SelectObject selectionObject;// Block type: Selection
    private NXOpen.BlockStyler.FaceCollector face_select0;// Block type: Face Collector

    private InputParameters InputParametersObj = null;

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public UI_ObjectSelectionToDisplayDetails(InputParameters inputParametersObj)
    {
        try
        {
            this.InputParametersObj = inputParametersObj;
            string dllPath = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location); //"C:\\Users\\arunk\\source\\repos\\ModelingPractice\\SourceCode\\bin\\Debug"
            string projectFolderPath =Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().CodeBase); //"file:\\C:\\Users\\arunk\\source\\repos\\ModelingPractice\\SourceCode\\bin\\Debug"
            Uri uriPath= new Uri(projectFolderPath); //{file:///C:/Users/arunk/source/repos/ModelingPractice/SourceCode/bin/Debug}
            string sourceCodeFolderPath = Directory.GetParent(uriPath.LocalPath).Parent.FullName; //"C:\\Users\\arunk\\source\\repos\\ModelingPractice\\SourceCode"
            string resourcesFolderPath = Path.Combine(sourceCodeFolderPath, "Resources"); //"C:\\Users\\arunk\\source\\repos\\ModelingPractice\\SourceCode\\Resources"
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            if (theSession.Parts.Work==null) 
            {
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, "Please open a part or an empty part to run this application.");
                return;
            }
            theDlxFileName =Path.Combine(resourcesFolderPath, "UI_ObjectSelectionToDisplayDetails.dlx");
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddCancelHandler(new NXOpen.BlockStyler.BlockDialog.Cancel(cancel_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    //public static void Main()
    //{
    //    UI_ObjectSelectionToDisplayDetails theUI_ObjectSelectionToDisplayDetails = null;
    //    try
    //    {
    //        theUI_ObjectSelectionToDisplayDetails = new UI_ObjectSelectionToDisplayDetails();
    //        // The following method shows the dialog immediately
    //        theUI_ObjectSelectionToDisplayDetails.Show();
    //    }
    //    catch (Exception ex)
    //    {
    //        //---- Enter your exception handling code here -----
    //        theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
    //    }
    //    finally
    //    {
    //        if(theUI_ObjectSelectionToDisplayDetails != null)
    //            theUI_ObjectSelectionToDisplayDetails.Dispose();
    //            theUI_ObjectSelectionToDisplayDetails = null;
    //    }
    //}
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
    // public static int GetUnloadOption(string arg)
    //{
    //    //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
    //     return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
    //    // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    //}
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //This method shows the dialog on the screen
    //------------------------------------------------------------------------------
    public NXOpen.UIStyler.DialogResponse Show()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
            selectionObject = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("selectionObject");
            face_select0 = (NXOpen.BlockStyler.FaceCollector)theDialog.TopBlock.FindBlock("face_select0");

            //var props = face_select0.GetProperties();
            //props.SetInteger("FaceRules", 0);
            //props.Dispose();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
            face_select0.Show = true;
            selectionObject.Show = true;
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
            if (selectionObject.GetSelectedObjects().Length>0) 
            {
                TaggedObject[] selectedObjs = selectionObject.GetSelectedObjects();
                InputParametersObj.SelectedObjs = selectedObjs.Length > 0 ? selectedObjs[0] : null;
            }
            if (face_select0.GetSelectedObjects().Length>0)
            {
                TaggedObject[] selectedObjs = face_select0.GetSelectedObjects();
                InputParametersObj.SelectedObjs = selectedObjs.Length > 0 ? selectedObjs[0] : null;
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if(block == selectionObject)
            {
                //---------Enter your code here-----------
                if (selectionObject.GetSelectedObjects().Length > 0)
                {
                    face_select0.Show = false;
                }
                else
                {
                    face_select0.Show = true;
                }
            }
            else if (block == face_select0)
            {
                //---------Enter your code here-----------
                if (face_select0.GetSelectedObjects().Length>0)
                {
                    selectionObject.Show = false;
                }
                else
                {
                    selectionObject.Show = true;
                }
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: cancel_cb
    //------------------------------------------------------------------------------
    public int cancel_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }
    
}
